### ISSUE TITLE
[Package request] Telegram

### ISSUE THREAD

**Issue by prateekmedia** [novus-package-manager/novus-packages#2]

**Comment by prateekmedia** [comment]
https://github.com/telegramdesktop/tdesktop/releases/tag/v3.0.1

**Comment by 0xPranavDoshi** [comment]
Hey, thanks for the suggestion. 

I will definitely add this package and let you know when it's done

**Comment by 0xPranavDoshi** [comment]
Hi, I have added Telegram as well as its portable version to the Novus manifest. 

Let me know if there are any issues or if you have any other suggestions.

**Comment by prateekmedia** [comment]
Thanks @ZaphodElevated, Have a nice day!
